version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./src:/var/www
            - ./php/php.ini:/usr/local/etc/php/php.ini
        networks: 
            - app-network
        
    
    mysql:
        image: mysql:5.7.33
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: laravel8
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: laravel8
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - app-network
        
    
    nginx:
        image: nginx:1.19.8-alpine
        restart: unless-stopped
        tty: true
        ports: 
            - 8100:80
        volumes: 
            - ./src:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network

    npm:
        image: node:current-alpine
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        environment:
            NODE_ENV: development
        command: "npm run dev"
        networks: 
            - app-network

    # frontend:
    #     image: node:current-alpine
    #     user: ${UID}:${UID}
    #     working_dir: /home/node/app
    #     volumes:
    #     - ./frontend:/home/node/app
    #     environment:
    #         NODE_ENV: development
    #     command: "npm run serve"